[package]
name = "ldscrs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive", "wrap_help"] }


[[bin]]
name = "munge_sumstats"
path = "src/munge_sumstats.rs"

[[bin]]
name = "ldscrs"
path = "src/main.rs"
